# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/jdk8:0.1.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
      JVM_OPTS: -Xmx3200m
      TERM: xterm
      _JAVA_OPTIONS: "-Xmx3g -Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw"

    steps:
      - checkout
      - run: cd VennFX && chmod +x gradlew
      
      - run: cd VennFX && ./gradlew check 
      
      - run: cd VennFX && ./gradlew dependencies



      # run tests! and build
      - run: cd VennFX && ./gradlew build --stacktrace
      - run: cd VennFX && ./gradlew clean test --stacktrace
