name: Java CI (Stefan)

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: cd VennFX && chmod +x gradlew
    - name: Build with Gradle
      run: cd VennFX && ./gradlew jar
    - name: JUnit Tests
      run: cd VennFX && ./gradlew test
